### PR TITLE
Integrated authentication

### PR DESCRIPTION
**Pull request by ifelere**
Installed laravel breeze started kit
Integrated login/session-aware items on navbar widget

### CODE REVIEW

**Review by yungxix — APPROVED** [review]

**Comment by yungxix** [comment]
Login implemented on the web version

**Comment by yungxix** [comment]
There was an error merging to the main branch

**Comment by ifelere** [comment]
Never mind. It's merged and I have pushed it

**Comment by yungxix** [comment]
Alright sir

**Pull request closed without merging**
